delete from Categories
delete from Orders
delete from OrderProducts
delete from ContactPersons
delete from Customers
delete from PaymentCards
delete from Suppliers
delete from Supplies
delete from SupplyProducts
delete from Products
delete from Sizes